{% set version = '1.1.4' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-backports
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/backports_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/backports/backports_{{ version }}.tar.gz
  sha256: ee4b5efef22fa7ef27d7983ffcd31db52f81e1fbb7189c6e89ee09b69349ff03

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base

  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('backports')"           # [not win]
    - "\"%R%\" -e \"library('backports')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/r-lib/backports
  license: GPL-2
  summary: ' Functions introduced or changed since R v3.0.0 are re-implemented in this package.
    The backports are conditionally exported in order to let R resolve the function
    name to either the implemented backport, or the respective base version, if available.
    Package developers can make use of new functions or arguments by selectively importing
    specific backports to support older installations.'

  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: backports
# Type: Package
# Title: Reimplementations of Functions Introduced Since R-3.0.0
# Version: 1.1.4
# Authors@R: c( person("Michel", "Lang", NULL, "michellang@gmail.com", role = c("cre", "aut"), comment = c(ORCID = "0000-0001-9754-0393")), person("R Core Team", role = "aut"))
# Maintainer: Michel Lang <michellang@gmail.com>
# Description:  Functions introduced or changed since R v3.0.0 are re-implemented in this package. The backports are conditionally exported in order to let R resolve the function name to either the implemented backport, or the respective base version, if available. Package developers can make use of new functions or arguments by selectively importing specific backports to support older installations.
# URL: https://github.com/r-lib/backports
# BugReports: https://github.com/r-lib/backports/issues
# License: GPL-2
# NeedsCompilation: yes
# ByteCompile: yes
# Depends: R (>= 3.0.0)
# Imports: utils
# Encoding: UTF-8
# RoxygenNote: 6.1.1
# Packaged: 2019-04-10 14:08:23 UTC; lang
# Author: Michel Lang [cre, aut] (<https://orcid.org/0000-0001-9754-0393>), R Core Team [aut]
# Repository: CRAN
# Date/Publication: 2019-04-10 14:55:26 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
