travis:
  secure:
    BINSTAR_TOKEN: k/46BxfPtLxc3lCTilr4dbx+ECHhQb9mRaFAuY6Y3ZKFqpL3fhyIgEXZtqhJ/qG7siGxdkeEpjPL07N3/q6DyD3Pth6IUuHMURInw0uPmlqatOTAjvFKJ6uY1bWZ7z55yrtwQEZO9reBu+Ed3pYm6dtlZm7NycJuhxepAJv3fIGjrV6vDspwsCbzJsM0CADh6q+XumPIPTkvf5idnaqIcK8bNu6pOat4UlWlE6Sz1CDZSi3Vmb3yblPbBU8JsDZY/HmS5TxC5vj/oUBGfHMcUMjQQvo4zrlc1yt5Iu8enyvCRk39bnOV4CUM9N/2YobGvFmdooL/3WNR/UHXLndsfhEKJAqreU0QJ9SDHj0Z3E6SskvUVzAF3ERVLTVzRqOevC/y9XOGxAJzcJefvp/vtTZMUpI/gb1SZ6738CvlMEPTmt/poIqRdu/X+Lyyo5Po11HyVUB2uSy9xrWT57ISIyJ1PJbIPvBg01NqokKmBqBSNb7sVGX4DnU+LRMBetgbT2TNCFWMO+L7fA5Yibu0dFcd8Lo6gpFScItmrIRlBite0gu+QWz9SA2NX6NenaHMaLGbKKnXRX9BqT38R2ZOgWO4V+uNFhf61jh4bjoe6AIuxlb+0kuKehvnueC5jx+k4zLK2HCQp5NAzJxCKR4hXi6OosDd+colnPQPW5XHY+I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
